services:
  - type: web
    name: slack-productivity-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://vibe-thrive-slackinsight-1.onrender.com