services:
  - type: web
    name: slack-productivity-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: productivity-db
          property: connectionString
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false

databases:
  - name: productivity-db
    databaseName: productivity
    user: productivity_user
    plan: starter